# Clave única y nombre del proyecto en tu servidor SonarQube
sonar.projectKey=FerremasFrontSQTest
sonar.projectName=FerremasFrontSQTest
sonar.projectVersion=1.0.0
sonar.host.url=http://localhost:9000

# Ubicación del código fuente (en Angular siempre es src)
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Excluir archivos de pruebas y configuraciones del análisis principal
sonar.exclusions=src/**/*.spec.ts, src/main.ts, src/environments/**

# Ubicación de los archivos de pruebas para que SonarQube los reconozca
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts

# Ruta al reporte de cobertura (LCOV) si ejecutas pruebas unitarias con Karma/Jest
# sonar.javascript.lcov.reportPaths=coverage/mi-app-angular/lcov.info